name: Terraform CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Validate, Scan, and Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: terraform
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Configure AWS Credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::716245435474:role/GitHubActions-Terraform-Role
          aws-region: us-east-1

      - name: Verify AWS Identity
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: aws sts get-caller-identity

      - name: Terraform Init
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform init

      - name: Terraform Validate
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform plan -no-color