name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy-auth-test:
    name: Test Deploy Role Authentication
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::716245435474:role/GitHubActions-Terraform-Deploy-Role
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity